name: Auto Translate HTML

on:
  push:
    branches: [main]

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Translate Korean HTML to English
        run: python translate_html.py index.html en/index.html en

      - name: Translate Korean HTML to Japanese
        run: python translate_html.py index.html ja/index.html ja

      - name: Commit translated files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add en/index.html ja/index.html
          git commit -m "Auto translated HTML pages"
          git push
        env:
          API_KEY: ${{ secrets.AZURE_TRANSLATOR_KEY }}
          ENDPOINT: ${{ secrets.AZURE_TRANSLATOR_ENDPOINT }}
          LOCATION: ${{ secrets.AZURE_TRANSLATOR_LOCATION }}
